Add include for add_const
Workaround a boost::range bug for boost 1.88 to 1.90
fixed in 1.91 (https://github.com/boostorg/range/pull/157)

Without this, with boost 1.89, I get:
```cpp
[  4%] Building CXX object CMakeFiles/fuse_core.dir/src/async_motion_model.cpp.o
In file included from /nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator.hpp:22,
                 from /nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/any_range.hpp:19,
                 from /build/fuse-release-release-jazzy-fuse_core-1.1.5-1/include/fuse_core/graph.hpp:49,
                 from /build/fuse-release-release-jazzy-fuse_core-1.1.5-1/include/fuse_core/async_motion_model.hpp:41,
                 from /build/fuse-release-release-jazzy-fuse_core-1.1.5-1/src/async_motion_model.cpp:39:
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:34:13: error: template argument 2 is invalid [-Wtemplate-body]
   34 |             >::type type;
      |             ^
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:34:14: error: expected identifier before '::' token [-Wtemplate-body]
   34 |             >::type type;
      |              ^~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:34:14: error: typedef name may not be a nested-name-specifier [-Wtemplate-body]
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:34:16: error: expected ';' at end of member declaration [-Wtemplate-body]
   34 |             >::type type;
      |                ^~~~
      |                    ;
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:34:21: error: declaration does not declare anything [-Wtemplate-body]
   34 |             >::type type;
      |                     ^~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp: In instantiation of 'struct boost::range_detail::any_incrementable_iterator_interface<const rclcpp::Time&, boost::any_iterator_buffer<64> >':
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:85:16:   required from 'struct boost::range_detail::any_single_pass_iterator_interface<const rclcpp::Time&, boost::any_iterator_buffer<64> >'
   85 |         struct any_single_pass_iterator_interface
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/detail/any_iterator_interface.hpp:111:16:   required from 'struct boost::range_detail::any_forward_iterator_interface<const rclcpp::Time&, boost::any_iterator_buffer<64> >'
  111 |         struct any_forward_iterator_interface
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/sanx9fg8mry8mq92zhlm5qvb83qlxrlx-gcc-15.2.0/include/c++/15.2.0/bits/stl_iterator_base_types.h:179:12:   recursively required by substitution of 'template<class _Iterator> struct std::__iterator_traits<_Iterator, std::__void_t<typename _Iterator::iterator_category, typename _Iterator::value_type, typename _Iterator::difference_type, typename _Iterator::pointer, typename _Iterator::reference> > [with _Iterator = boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> >]'
  179 |     struct iterator_traits
      |            ^~~~~~~~~~~~~~~
/nix/store/sanx9fg8mry8mq92zhlm5qvb83qlxrlx-gcc-15.2.0/include/c++/15.2.0/bits/stl_iterator_base_types.h:179:12:   required from 'struct std::iterator_traits<boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> > >'
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/iterator/iterator_categories.hpp:51:7:   required by substitution of 'template<class Iterator> using boost::iterators::iterator_traversal_t = boost::iterators::iterator_category_to_traversal_t<typename std::iterator_traits<_Iterator>::iterator_category> [with Iterator = boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> >]'
   51 | using iterator_traversal_t = iterator_category_to_traversal_t<
      |       ^~~~~~~~~~~~~~~~~~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/iterator/iterator_categories.hpp:58:11:   required from 'struct boost::iterators::iterator_traversal<boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> > >'
   58 |     using type = iterator_traversal_t< Iterator >;
      |           ^~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/iterator_range_core.hpp:161:5:   required from 'struct boost::iterator_range_detail::pure_iterator_traversal<boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> > >'
  161 |     traversal_t;
      |     ^~~~~~~~~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/iterator_range_core.hpp:437:15:   required from 'class boost::iterator_range<boost::range_detail::any_iterator<const rclcpp::Time, boost::iterators::forward_traversal_tag, const rclcpp::Time&, long int, boost::any_iterator_buffer<64> > >'
  437 |         class iterator_range
      |               ^~~~~~~~~~~~~~
/nix/store/4qaj1kkf1p3al8z190px12ma6r8jbgqj-boost-1.89.0-dev/include/boost/range/any_range.hpp:83:15:   required from 'class boost::range_detail::any_range<const rclcpp::Time, boost::iterators::forward_traversal_tag>'
   83 |         class any_range
      |               ^~~~~~~~~
/build/fuse-release-release-jazzy-fuse_core-1.1.5-1/include/fuse_core/transaction.hpp:126:44:   required from here
  126 |   const_stamp_range involvedStamps() const {return involved_stamps_;}
      |                                            ^
```